version: "3.8"

services:
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"

  noticationsdata:
    image: redis:6.2.2-alpine
    volumes:
      - lounge-noticationsdata:/data
    privileged: true
    command:
      - /bin/sh
      - -c
      - | 
        sysctl -w vm.overcommit_memory=1 && redis-server
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "6380:6379"

  signalrbackplane:
    image: redis:6.2.2-alpine
    volumes:
      - lounge-signalrbackplane:/data
    privileged: true
    command:
      - /bin/sh
      - -c
      - | 
        sysctl -w vm.overcommit_memory=1 && redis-server
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "6379:6379"

  usersdata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    volumes:
      - lounge-usersdata:/var/opt/mssql
    ports:
      - "5433:1433"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15672:15672"
      - "5672:5672"

  users-api:
    image: ${REGISTRY:-lounge}/users.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Users/Users.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityAuthority=${LOUNGE_IDENTITY_AUTHORITY}
      - IdentityAudience=https://api.lounge.com
      - ConnectionString=Server=usersdata;Database=Lounge.Services.UsersDb;User Id=sa;Password=Pass@word
      - GrpcNotifications=http://notifications-api:81
      - EventBusConnection=rabbitmq
      - EventBusUserName=${RABBITMQ_DEFAULT_USER}
      - EventBusPassword=${RABBITMQ_DEFAULT_PASS}
      - PATH_BASE=/users-api
    ports:
      - "5100:80"
      - "9100:81"
    depends_on:
      - usersdata
      - rabbitmq

  notifications-api:
    image: ${REGISTRY:-lounge}/notifications.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Notifications/Notifications.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityAuthority=${LOUNGE_IDENTITY_AUTHORITY}
      - IdentityAudience=https://api.lounge.com
      - SignalRBackplaneConnectionString=signalrbackplane
      - RedisConnectionString=noticationsdata
      - GrpcUsers=http://users-api:81
      - EventBusConnection=rabbitmq
      - EventBusUserName=${RABBITMQ_DEFAULT_USER}
      - EventBusPassword=${RABBITMQ_DEFAULT_PASS}
      - PATH_BASE=/notifications-api
    ports:
      - "5101:80"
      - "9101:81"
    depends_on:
      - rabbitmq
      - noticationsdata
      - signalrbackplane

volumes:
  lounge-usersdata:
    external: false
  lounge-noticationsdata:
    external: false
  lounge-signalrbackplane:
    external: false